import { defineConfig } from '@pandacss/dev';

export default defineConfig({
  // Whether to use css reset
  preflight: true,

  // Where to look for your css declarations
  include: ['./src/**/*.{js,jsx,ts,tsx}'],

  // Files to exclude
  exclude: [],

  // Useful for theme customization
  theme: {
    extend: {
      tokens: {
        colors: {
          base: { value: 'var(--colors-base)' },
          surface: { value: 'var(--colors-surface)' },
          overlay: { value: 'var(--colors-overlay)' },
          muted: { value: 'var(--colors-muted)' },
          subtle: { value: 'var(--colors-subtle)' },
          text: { value: 'var(--colors-text)' },
          love: { value: 'var(--colors-love)' },
          gold: { value: 'var(--colors-gold)' },
          rose: { value: 'var(--colors-rose)' },
          pine: { value: 'var(--colors-pine)' },
          foam: { value: 'var(--colors-foam)' },
          iris: { value: 'var(--colors-iris)' },
          'highlight-low': { value: 'var(--colors-highlight-low)' },
          'highlight-med': { value: 'var(--colors-highlight-med)' },
          'highlight-high': { value: 'var(--colors-highlight-high)' },
        },
        fontSizes: {
          xs: { value: 'var(--font-sizes-xs)' },
          sm: { value: 'var(--font-sizes-sm)' },
          md: { value: 'var(--font-sizes-md)' },
          lg: { value: 'var(--font-sizes-lg)' },
          xl: { value: 'var(--font-sizes-xl)' },
          '2xl': { value: 'var(--font-sizes-2xl)' },
          '3xl': { value: 'var(--font-sizes-3xl)' },
          '4xl': { value: 'var(--font-sizes-4xl)' },
          '5xl': { value: 'var(--font-sizes-5xl)' },
          '6xl': { value: 'var(--font-sizes-6xl)' },
          '7xl': { value: 'var(--font-sizes-7xl)' },
          '8xl': { value: 'var(--font-sizes-8xl)' },
        },
        sizes: {
          0: { value: '0px' },
          '0.5': { value: '2px' },
          1: { value: '4px' },
          '1.5': { value: '6px' },
          2: { value: '8px' },
          '2.5': { value: '10px' },
          3: { value: '12px' },
          '3.5': { value: '14px' },
          4: { value: '16px' },
          '4.5': { value: '18px' },
          5: { value: '20px' },
          '5.5': { value: '22px' },
          6: { value: '24px' },
          7: { value: '28px' },
          8: { value: '32px' },
          9: { value: '36px' },
          10: { value: '40px' },
          11: { value: '44px' },
          12: { value: '48px' },
          14: { value: '56px' },
          16: { value: '64px' },
          20: { value: '80px' },
          24: { value: '96px' },
          28: { value: '112px' },
          32: { value: '128px' },
          36: { value: '144px' },
          40: { value: '160px' },
          44: { value: '176px' },
          48: { value: '192px' },
          52: { value: '208px' },
          56: { value: '224px' },
          60: { value: '240px' },
          64: { value: '256px' },
          72: { value: '288px' },
          80: { value: '320px' },
          96: { value: '384px' },
          xs: { value: '320px' },
          sm: { value: '384px' },
          md: { value: '448px' },
          lg: { value: '512px' },
          xl: { value: '576px' },
          '2xl': { value: '672px' },
          '3xl': { value: '768px' },
          '4xl': { value: '896px' },
          '5xl': { value: '1024px' },
          '6xl': { value: '1152px' },
          '7xl': { value: '1280px' },
          '8xl': { value: '1440px' },
        },
        spacing: {
          0: { value: '0px' },
          '0.5': { value: '2px' },
          1: { value: '4px' },
          '1.5': { value: '6px' },
          2: { value: '8px' },
          '2.5': { value: '10px' },
          3: { value: '12px' },
          '3.5': { value: '14px' },
          4: { value: '16px' },
          '4.5': { value: '18px' },
          5: { value: '20px' },
          '5.5': { value: '22px' },
          6: { value: '24px' },
          7: { value: '28px' },
          8: { value: '32px' },
          9: { value: '36px' },
          10: { value: '40px' },
          11: { value: '44px' },
          12: { value: '48px' },
          14: { value: '56px' },
          16: { value: '64px' },
          20: { value: '80px' },
          24: { value: '96px' },
          28: { value: '112px' },
          32: { value: '128px' },
          36: { value: '144px' },
          40: { value: '160px' },
          44: { value: '176px' },
          48: { value: '192px' },
          52: { value: '208px' },
          56: { value: '224px' },
          60: { value: '240px' },
          64: { value: '256px' },
          72: { value: '288px' },
          80: { value: '320px' },
          96: { value: '384px' },
        },
      },
    },
  },

  // The output directory for your css system
  outdir: 'styled-system',
});
