import { defineConfig } from 'vite-plus';

export default defineConfig({
  staged: {
    '*': 'vp check --fix',
    '*.{html,jsx,tsx}': 'markuplint "src/**/*.{html,jsx,tsx}" --fix --problem-only',
    '.github/workflows/**/*.{yml,yaml}': ['pinact run -u --min-age 7', 'ghalint run', 'actionlint'],
  },
  fmt: {
    semi: true,
    singleQuote: true,
    sortImports: {
      groups: [
        ['type-builtin', 'value-builtin'],
        ['type-external', 'type-internal', 'value-external', 'value-internal'],
        [
          'type-index',
          'type-parent',
          'type-sibling',
          'value-index',
          'value-parent',
          'value-sibling',
        ],
        ['unknown'],
      ],
      newlinesBetween: true,
      order: 'asc',
    },
    sortPackageJson: true,
    trailingComma: 'all',
  },
  lint: {
    plugins: ['nextjs', 'typescript'],
    jsPlugins: [
      '@pandacss/eslint-plugin',
      'eslint-plugin-command',
      'eslint-plugin-react-compiler',
      'eslint-plugin-security',
    ],
    options: {
      typeAware: true,
      typeCheck: true,
    },
    categories: {
      correctness: 'error',
      perf: 'warn',
      suspicious: 'warn',
    },
    env: {
      builtin: true,
    },
    ignorePatterns: ['.next/**', 'out/**', 'build/**', 'next-env.d.ts', 'styled-system'],
    rules: {
      'no-array-constructor': 'error',
      'no-unused-expressions': 'warn',
      'no-unused-vars': 'warn',
      '@pandacss/file-not-included': 'error',
      '@pandacss/no-config-function-in-source': 'error',
      '@pandacss/no-debug': 'warn',
      '@pandacss/no-dynamic-styling': 'warn',
      '@pandacss/no-invalid-nesting': 'error',
      '@pandacss/no-invalid-token-paths': 'error',
      '@pandacss/no-property-renaming': 'warn',
      '@pandacss/no-unsafe-token-fn-usage': 'warn',
      '@pandacss/no-deprecated-tokens': 'warn',
      'command/command': 'error',
      'react-compiler/react-compiler': 'error',
      'security/detect-buffer-noassert': 'warn',
      'security/detect-child-process': 'warn',
      'security/detect-disable-mustache-escape': 'warn',
      'security/detect-eval-with-expression': 'warn',
      'security/detect-new-buffer': 'warn',
      'security/detect-no-csrf-before-method-override': 'warn',
      'security/detect-non-literal-fs-filename': 'warn',
      'security/detect-non-literal-regexp': 'warn',
      'security/detect-non-literal-require': 'warn',
      'security/detect-object-injection': 'warn',
      'security/detect-possible-timing-attacks': 'warn',
      'security/detect-pseudoRandomBytes': 'warn',
      'security/detect-unsafe-regex': 'warn',
      'security/detect-bidi-characters': 'warn',
      'nextjs/google-font-display': 'warn',
      'nextjs/google-font-preconnect': 'warn',
      'nextjs/next-script-for-ga': 'warn',
      'nextjs/no-async-client-component': 'warn',
      'nextjs/no-before-interactive-script-outside-document': 'warn',
      'nextjs/no-css-tags': 'warn',
      'nextjs/no-head-element': 'warn',
      'nextjs/no-html-link-for-pages': 'error',
      'nextjs/no-img-element': 'warn',
      'nextjs/no-page-custom-font': 'warn',
      'nextjs/no-styled-jsx-in-document': 'warn',
      'nextjs/no-sync-scripts': 'error',
      'nextjs/no-title-in-document-head': 'warn',
      'nextjs/no-typos': 'warn',
      'nextjs/no-unwanted-polyfillio': 'warn',
      'nextjs/inline-script-id': 'error',
      'nextjs/no-assign-module-variable': 'error',
      'nextjs/no-document-import-in-page': 'error',
      'nextjs/no-duplicate-head': 'error',
      'nextjs/no-head-import-in-document': 'error',
      'nextjs/no-script-component-in-head': 'error',
      'typescript/ban-ts-comment': 'error',
      'typescript/no-duplicate-enum-values': 'error',
      'typescript/no-empty-object-type': 'error',
      'typescript/no-explicit-any': 'error',
      'typescript/no-extra-non-null-assertion': 'error',
      'typescript/no-misused-new': 'error',
      'typescript/no-namespace': 'error',
      'typescript/no-non-null-asserted-optional-chain': 'error',
      'typescript/no-require-imports': 'error',
      'typescript/no-this-alias': 'error',
      'typescript/no-unnecessary-type-constraint': 'error',
      'typescript/no-unsafe-declaration-merging': 'error',
      'typescript/no-unsafe-function-type': 'error',
      'typescript/no-wrapper-object-types': 'error',
      'typescript/prefer-as-const': 'error',
      'typescript/prefer-namespace-keyword': 'error',
      'typescript/triple-slash-reference': 'error',
      'typescript/no-floating-promises': 'error',
      'typescript/no-misused-promises': 'error',
      'typescript/await-thenable': 'error',
      'typescript/no-unsafe-argument': 'error',
      'typescript/no-unsafe-assignment': 'error',
      'typescript/no-unsafe-call': 'error',
      'typescript/no-unsafe-return': 'error',
      'typescript/no-unsafe-member-access': 'error',
      'typescript/no-unnecessary-type-assertion': 'warn',
      'typescript/no-unnecessary-condition': 'warn',
      'typescript/prefer-nullish-coalescing': 'warn',
      'typescript/prefer-optional-chain': 'warn',
      'typescript/switch-exhaustiveness-check': 'error',
    },
    overrides: [
      {
        files: ['**/*.{js,jsx,mjs,ts,tsx,mts,cts}'],
        rules: {
          'react/display-name': 'error',
          'react/jsx-key': 'error',
          'react/jsx-no-comment-textnodes': 'error',
          'react/jsx-no-duplicate-props': 'error',
          'react/jsx-no-target-blank': 'off',
          'react/jsx-no-undef': 'error',
          'react/no-children-prop': 'error',
          'react/no-danger-with-children': 'error',
          'react/no-direct-mutation-state': 'error',
          'react/no-find-dom-node': 'error',
          'react/no-is-mounted': 'error',
          'react/no-render-return-value': 'error',
          'react/no-string-refs': 'error',
          'react/no-unescaped-entities': 'error',
          'react/no-unknown-property': 'off',
          'react/no-unsafe': 'off',
          'react/react-in-jsx-scope': 'off',
          'react/require-render-return': 'error',
          'import/no-anonymous-default-export': 'warn',
          'import/no-unassigned-import': ['warn', { allow: ['**/*.css'] }],
          'jsx-a11y/alt-text': [
            'warn',
            {
              elements: ['img'],
              img: ['Image'],
            },
          ],
          'jsx-a11y/aria-props': 'warn',
          'jsx-a11y/aria-proptypes': 'warn',
          'jsx-a11y/aria-unsupported-elements': 'warn',
          'jsx-a11y/role-has-required-aria-props': 'warn',
          'jsx-a11y/role-supports-aria-props': 'warn',
          'nextjs/no-html-link-for-pages': 'warn',
          'nextjs/no-sync-scripts': 'warn',
          'react/rules-of-hooks': 'error',
          'react/exhaustive-deps': 'warn',
        },
        globals: {
          AudioWorkletGlobalScope: 'readonly',
          AudioWorkletProcessor: 'readonly',
          currentFrame: 'readonly',
          currentTime: 'readonly',
          registerProcessor: 'readonly',
          sampleRate: 'readonly',
          WorkletGlobalScope: 'readonly',
        },
        plugins: ['react', 'import', 'jsx-a11y'],
        env: {
          browser: true,
          node: true,
        },
      },
      {
        files: ['**/*.{js,jsx,mjs,cjs,ts,tsx,mts,cts}'],
        rules: {
          'react-js/jsx-sort-props': [
            'warn',
            {
              callbacksLast: true,
              shorthandFirst: true,
              ignoreCase: true,
              reservedFirst: true,
            },
          ],
        },
        jsPlugins: [
          {
            name: 'react-js',
            specifier: 'eslint-plugin-react',
          },
        ],
        env: {
          browser: true,
        },
      },
      {
        files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts'],
        rules: {
          'constructor-super': 'off',
          'getter-return': 'off',
          'no-class-assign': 'off',
          'no-const-assign': 'off',
          'no-dupe-class-members': 'off',
          'no-dupe-keys': 'off',
          'no-func-assign': 'off',
          'no-import-assign': 'off',
          'no-new-native-nonconstructor': 'off',
          'no-obj-calls': 'off',
          'no-redeclare': 'off',
          'no-setter-return': 'off',
          'no-this-before-super': 'off',
          'no-undef': 'off',
          'no-unreachable': 'off',
          'no-unsafe-negation': 'off',
          'no-var': 'error',
          'no-with': 'off',
          'prefer-const': 'error',
          'prefer-rest-params': 'error',
          'prefer-spread': 'error',
        },
      },
      {
        files: ['**/*.{js,jsx,mjs,cjs,ts,tsx,mts,cts}'],
        rules: {
          'react-you-might-not-need-an-effect/no-empty-effect': 'warn',
          'react-you-might-not-need-an-effect/no-adjust-state-on-prop-change': 'warn',
          'react-you-might-not-need-an-effect/no-reset-all-state-on-prop-change': 'warn',
          'react-you-might-not-need-an-effect/no-event-handler': 'warn',
          'react-you-might-not-need-an-effect/no-pass-live-state-to-parent': 'warn',
          'react-you-might-not-need-an-effect/no-pass-data-to-parent': 'warn',
          'react-you-might-not-need-an-effect/no-initialize-state': 'warn',
          'react-you-might-not-need-an-effect/no-chain-state-updates': 'warn',
          'react-you-might-not-need-an-effect/no-derived-state': 'warn',
        },
        jsPlugins: ['eslint-plugin-react-you-might-not-need-an-effect'],
        globals: {
          AudioWorkletGlobalScope: 'readonly',
          AudioWorkletProcessor: 'readonly',
          currentFrame: 'readonly',
          currentTime: 'readonly',
          registerProcessor: 'readonly',
          sampleRate: 'readonly',
          WorkletGlobalScope: 'readonly',
        },
        env: {
          browser: true,
        },
      },
      {
        files: ['**/*.stories.@(ts|tsx|js|jsx|mjs|cjs)', '**/*.story.@(ts|tsx|js|jsx|mjs|cjs)'],
        rules: {
          'storybook/await-interactions': 'error',
          'storybook/context-in-play-function': 'error',
          'storybook/default-exports': 'error',
          'storybook/hierarchy-separator': 'warn',
          'storybook/no-redundant-story-name': 'warn',
          'storybook/no-renderer-packages': 'error',
          'storybook/prefer-pascal-case': 'warn',
          'storybook/story-exports': 'error',
          'storybook/use-storybook-expect': 'error',
          'storybook/use-storybook-testing-library': 'error',
          'import/no-anonymous-default-export': 'off',
          'react/rules-of-hooks': 'off',
        },
        jsPlugins: ['eslint-plugin-storybook'],
        plugins: ['react', 'import'],
      },
      {
        files: ['.storybook/main.@(js|cjs|mjs|ts)'],
        rules: {
          'storybook/no-uninstalled-addons': 'error',
        },
        jsPlugins: ['eslint-plugin-storybook'],
      },
    ],
  },
});
