import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import { ReactNode } from 'react';

import { MswProvider } from '../libs/msw/msw-provider';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <MswProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </MswProvider>
      </body>
    </html>
  );
}
